<?
/**
 * @var string $addressSelection
 * @var array  $deliveryOptionList
 */
?>
<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-xs-9">
                <div class="cart-page">
                    <div class="cart-breadcrumbs">
                        <ul>
                            <li class=""><a href="/cart">CART</a></li>
                            <li class="active"><a href="#">DELIVERY</a></li>
                            <li class=""><a href="#">PAYMENT</a></li>
                            <li class=""><a href="#">RECEIPT</a></li>
                        </ul>
                    </div>
                    <h1>Enter <span>Delivery Address</span></h1>
                    <div class="delivery-tabs tabs">
                        <ul id="deliveryOptions">
                            <li><a href="#pick-up-in-store" data-cargo="1"><span></span>Pick up in Kernel & Roast Store</a></li>
                            <li><a href="#deliver-to-address" data-cargo="2"><span></span>Deliver to My Address</a></li>
                        </ul>
                        <div id="deliver-to-address">
                            <?= $addressSelection ?>
                        </div>
                        <div id="pick-up-in-store"></div>
                    </div>
                    <div class="cart-footer add-2x-top">
                        <div class="row">
                            <div class="col-xs-4"><a href="/cart" class="btn btn-double-bordered btn-gray-bordered btn-font-medium half-bottom">BACK TO CART</a></div>
                            <div class="col-xs-4 pull-right"><a href="javascript:" class="btn btn-red btn-font-bold continueBtn">PROCEED TO CHECKOUT</a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-3" id="cartSummary">
            </div>
        </div>
    </div>
</div>
