<?
/**
 * @var array                                          $cityList
 * @var array                                          $townListDelivery
 * @var array                                          $districtListDelivery
 * @var array                                          $townListInvoice
 * @var array                                          $districtListInvoice
 * @var \TeknoETicaret\Shopping\Object\Checkout        $checkout
 * @var \TeknoETicaret\Shopping\Object\DeliveryAddress $deliveryAddress
 * @var \TeknoETicaret\Shopping\Object\InvoiceInfo     $invoiceInfo
 */
?>
<script>
    $(document).ready(function () {
        var map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: 41.8688, lng: 29.2195},
            zoom: 13,
            mapTypeId: 'roadmap'
        });
        var input = document.getElementById('places-input');
        var searchBox = new google.maps.places.SearchBox(input);
        searchBox.addListener('places_changed', function () {
        });
    });
</script>
<div class="row" id="search-place">
    <div class="col-xs-10">
        <div class="form-module">
            <form autocomplete="off">
                <fieldset>
                    <div class="form-row">
                        <div class="form-row-title font-medium">Start typing your Street Address</div>
                        <div class="form-row-content">
                            <label>
                                <input type="text" class="input-text" id="places-input" placeholder="" autocomplete="">
                            </label>
                            <div id="map" style="height:0;width:0;display:none;position:fixed;top:-9999px;left:-9999px;opacity:0;visibility:hidden;"></div>
                        </div>
                        <div class="form-row-title">Can’t find your address? <a style="color:#e64a30" href="#" class="toggle-address">Enter it manually</a></div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>
<div class="row" id="address-manual" style="display:none;">
    <form class="form-horizontal" role="form" id="addressForm" action="/checkout/deliveryNewAddress" method="post">
        <input type="hidden" name="form" value="newAddress"/>
        <input type="hidden" id="deliveryOptionId" name="delivery_option" value="<?= $checkout->deliveryOptionId ?>"/>
        <fieldset>
            <div class="col-xs-6">
                <div class="form-module">
                    <div class="form-row">
                        <div class="form-row-title">Street Address<span class="required">*</span></div>
                        <div class="form-row-content">
                            <label>
                                <input name="street" type="text" class="input-text">
                            </label>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-row-title">Apartment Number <span>(optional)</span></div>
                        <div class="form-row-content">
                            <label>
                                <input name="apartment" type="text" class="input-text">
                            </label>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-row-title">Business Name <span>(optional)</span></div>
                        <div class="form-row-content">
                            <label>
                                <input name="business_name" type="text" class="input-text" placeholder="Business Name">
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-4">
                            <div class="form-row">
                                <div class="form-row-title">Postal Code<span class="required">*</span></div>
                                <div class="form-row-content">
                                    <label>
                                        <input type="text" name="postcode_1" class="input-text" placeholder="">
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-8">
                            <div class="form-row">
                                <div class="form-row-title">City<span class="required">*</span></div>
                                <div class="form-row-content">
                                    <label>
                                        <select name="city_id_1">
                                            <option value="">Select</option>
                                            <option value="1">London</option>
                                            <option value="2">Manchester</option>
                                        </select>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-module">
                    <div class="form-row">
                        <div class="form-row-title">Phone Number<span class="required">*</span></div>
                        <div class="form-row-content">
                            <label>
                                <input type="tel" name="phone_number_1" class="input-text" placeholder="Phone Number">
                            </label>
                        </div>
                        <div class="terms-agree-line"><br>We will contact using this number when we arrive</div>
                    </div>
                    <div class="form-row">
                        <div class="form-row-title">Instructions for Delivery <span>(optional)</span></div>
                        <div class="form-row-content">
                            <label>
                                <textarea class="input-text" placeholder="(e.g. your door code)"></textarea>
                            </label>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-row-title">&nbsp;</div>
                        <div class="terms-agree-line"><span class="required">*</span> Required fields</div>
                    </div>
                </div>
                <input type="hidden" id="invoiceCheckBox" name="invoice_same_address" value="1">
            </div>
        </fieldset>
    </form>
</div>
<script>
    $(function () {
        $(document).on("click", ".continueBtn", function () {
            $('form#addressForm').submit();
        });
    });
</script>
