<?
/**
 * @var \TeknoETicaret\Shopping\Cart\Cart              $cart
 * @var \TeknoETicaret\Shopping\Object\Checkout        $checkout
 * @var \TeknoETicaret\Shopping\Object\DeliveryAddress $deliveryAddress
 * @var \TeknoETicaret\Shopping\Object\InvoiceInfo     $invoiceInfo
 * @var string|null                                    $buttonClass
 * @var string|null                                    $buttonTitle
 * @var string                                         $paymentMethodName
 * @var bool                                           $showAggrements
 * @var bool                                           $addressesSet
 * @var bool                                           $changeButtons
 * @var array                                          $summaryDetails
 */
?>
<div class="cart-side-basket">
    <div class="cart-side-title">SUMMARY</div>
    <div class="cart-side-basket-content">
        <div class="cart-side-basket-title">Your Cart</div>
        <table>
            <? foreach ($cart->getProducts() as $cartProduct) {
                $product = $cartProduct->getProduct() ?>
                <tr>
                    <td class="product-thumbnail"><img src="<?= $product->getPhoto('thumb') ?>"></td>
                    <td class="product-info">
                        <?= $product->full_name ?>
                        <div class="product-meta">
                            <div class="product-quantity"><input type="text" value="<?= $cartProduct->getQuantity() ?>"></div>
                            <div class="product-price">£<?= icms::format_money($cartProduct->getTotalPrice(), null) ?></div>
                        </div>
                    </td>
                </tr>
            <? } ?>
            <tr class="collaterals">
                <td colspan="2" style="text-align:right;"><span>TOTAL</span>£<?= icms::format_money(max($cart->getTotalPrice() - $cart->getMemberBalance(), 0), null) ?></td>
            </tr>
        </table>
    </div>
</div>
