<div id="CreditCardError" style="display: none">
    <div class="alert alert-danger"></div>
</div>
<div class="form-module credit-card">
    <form id="chargeForm" method="post" action="/checkout/paymentSubmit/CreditCard">
        <input type="hidden" name="form" value="checkout-creditcard">
        <input type="hidden" name="selected_installment_id" value="0" id="selected_installment_id">
        <input type="hidden" name="force_3d_secure" value="0" id="force_3d_secure">
        <fieldset>
            <div class="row">
                <div class="col-xs-6">
                    <div class="form-row">
                        <div class="form-row-title">Cardholder Name</div>
                        <div class="form-row-content">
                            <label>
                                <input type="text" name="card_owner" class="input-text" placeholder="">
                            </label>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-row-title">Card Number</div>
                        <div class="form-row-content">
                            <label>
                                <input name="card_number" type="tel" class="input-text" placeholder="">
                            </label>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-row-title">Expiration Date</div>
                        <div class="row">
                            <div class="col-xs-6">
                                <div class="form-row-content">
                                    <label>
                                        <select name="expire_month">
                                            <option value="AA">Month</option>
                                            <option value="01">01</option>
                                            <option value="02">02</option>
                                            <option value="03">03</option>
                                            <option value="04">04</option>
                                            <option value="05">05</option>
                                            <option value="06">06</option>
                                            <option value="07">07</option>
                                            <option value="08">08</option>
                                            <option value="09">09</option>
                                            <option value="10">10</option>
                                            <option value="11">11</option>
                                            <option value="12">12</option>
                                        </select>
                                    </label>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div class="form-row-content">
                                    <label>
                                        <select name="expire_year">
                                            <option value="YY">Year</option><?
                                            $maxyear = date('Y') + 20;
                                            for ($i = date('Y'); $i < $maxyear; $i++) {
                                                echo '<option value="' . $i . '">' . $i . '</option>';
                                            } // for
                                            ?></select>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-row-title">CVV<a href="#" class="question-mark">?</a></div>
                        <div class="row">
                            <div class="col-xs-6">
                                <div class="form-row-content">
                                    <label>
                                        <input name="cvc" type="tel" class="input-text" placeholder="3 digits">
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</div>
<div id="CreditCardProcessing" style="display: none">
    <h2>PROCESSING PAYMENT</h2>
    <div class="clearfix">
        <div class="col-xs-offset-2 col-xs-8">
            <div class="text-center b"><span class="totalChargeAmount"></span> is being charged from your credit card..</div>
            <div class="progress progress-striped active mt">
                <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
            </div>
        </div>
    </div>
    <div class="text-center">Please do not close the window until the transaction is completed.</div>
</div>
