<?
/**
 * @var array                             $paymentTabs
 * @var \TeknoETicaret\Shopping\Cart\Cart $cart
 */
?>
<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-xs-9">
                <div class="cart-page">
                    <div class="cart-breadcrumbs">
                        <ul>
                            <li class=""><a href="/cart">CART</a></li>
                            <li class=""><a href="/checkout/delivery">DELIVERY</a></li>
                            <li class="active"><a href="#">PAYMENT</a></li>
                            <li class=""><a href="#">RECEIPT</a></li>
                        </ul>
                    </div>
                    <h1>Payment <span>Details</span></h1>
                    <div class="delivery-tabs tabs">
                        <ul id="paymentMethods">
                            <li><a href="#credit-card" data-url="/checkout/paymentForm/CreditCard" data-toggle="tab" data-paymentmethod="CreditCard">
                                    <span></span>Pay with Credit Card or Debit Card</a></li>
                            <li><a href="#paypal" class="paypal" data-url="/checkout/paymentForm/PayPal" data-toggle="tab" data-paymentmethod="PayPal">
                                    <span></span>Pay with Your PayPal Account<i>Log in to your account to complete this purchase</i></a></li>
                        </ul>
                        <div id="paymentOptions" class="checkoutContent">
                            <div id="credit-card"></div>
                            <div id="paypal"></div>
                        </div>
                    </div>
                    <div class="cart-footer add-2x-top">
                        <div class="row">
                            <div class="col-xs-3"><a href="/checkout/delivery" class="btn btn-double-bordered btn-gray-bordered btn-font-medium half-bottom">BACK TO ADDRESS</a>
                            </div>
                            <div class="col-xs-3 pull-right"><a href="javascript:" class="btn btn-red btn-font-bold continueBtn">
                                    PAY £<?= icms::format_money($cart->getTotalPrice(), null) ?></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-3" id="cartSummary">
            </div>
        </div>
    </div>
</div>
