<?
/**
 * @var string            $title
 * @var blog_post_model[] $blogPosts
 */
$colCount = floor(12 / count($blogPosts));
?>
<section>
    <h2 class="with-icon blog"><?= $title ?></h2>
    <div class="blog-posts">
        <div class="row">
            <? foreach ($blogPosts as $blogPost) {  ?>
                <div class="col-xs-<?= $colCount ?>">
                    <a href="<?= link::toBlogPost($blogPost) ?>" class="blog-post-item">
                        <div class="blog-post-item-img">
                            <img src="<?= image::getBlogPostCover($blogPost->blog_post_id) ?>">
                        </div>
                        <div class="blog-post-item-content">
                            <h3><?= $blogPost->post_title ?></h3>
                            <div class="blog-post-item-text">
                                <p><?= $blogPost->getContentPreview() ?></p>
                            </div>
                            <div class="read-more">READ FULL STORY</div>
                        </div>
                    </a>
                </div>
            <?  } ?>
        </div>
    </div>
</section>
