<?
/**
 * @var string            $title
 * @var blog_post_model[] $blogPosts
 */
?>
<div class="widget widgetBlogPosts">
    <table class="table table-bordered">
        <? if (!empty($title)) { ?>
            <thead>
            <tr>
                <th><?= $title ?></th>
            </tr>
            </thead>
        <? } ?>
        <tbody>
        <? foreach ($blogPosts as $blogPost) { ?>
            <tr>
                <td><a href="<?= link::toBlogPost($blogPost) ?>"><?= $blogPost->post_title ?></a></td>
            </tr>
        <? } ?>
        </tbody>
    </table>
</div>
