<?
/**
 * @var int             $id
 * @var string          $title
 * @var \product_item[] $products
 */
?>
<section>
    <h2><?= $title ?></h2>
    <div class="product-recommendation carousel">
        <ul>
            <? foreach ($products as $key => $product) { ?>
                <li>
                    <?= $product->generate() ?>
                </li>
            <? } ?>
        </ul>
    </div>
</section>

